[package]
name = "mqtt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2.12"
logger = { path = "../logger"}

[lib]
name = "mqtt"
path = "src/lib.rs"

